### ISSUE TITLE
rollout status not return a message

### ISSUE THREAD

**Issue by krol3** [kubernetes/kubectl#1050]
#### What happened:

The client don't return a message. After use the command.
```
kubectl rollout status deployment 

```
#### What you expected to happen:
I expected the same behavior of the other commands of rollout. For example
```
kubectl rollout history deployment 
deployment.apps/nginx191 
REVISION  CHANGE-CAUSE
1         <none>
``` 

#### How to reproduce it (as minimally and precisely as possible):
```
kubectl rollout status deployment 

```
#### Environment:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by rikatz** [comment]
/assign
Will take a look during weekend :)

**Comment by rikatz** [comment]
confirmed here, let me take a look into this

**Comment by eddiezane** [comment]
I think this is resolved by https://github.com/kubernetes/kubernetes/pull/99758?

cc @aramperes

**Comment by aramperes** [comment]
> I think this is resolved by [kubernetes/kubernetes#99758](https://github.com/kubernetes/kubernetes/pull/99758)?
> 
> cc @aramperes

As far as I can tell it's not; the error message change was not applied to the `rollout status` command.

`kubectl rollout status` still hangs for anything other than selecting 1 resource by name. `--watch` also seems to not work (it exits with e.g. `deployment "my-app" successfully rolled out`)

**Comment by lauchokyip** [comment]
Seem like this PR would fix it , but need some changes @eddiezane 
https://github.com/kubernetes/kubernetes/pull/102041

**Comment by aramperes** [comment]
/reopen
/remove-lifecycle rotten
/assign

I'd like to help with this; as I understand the intent is that `rollout status` only exits once all matched resources have a completed rollout?
