### ISSUE TITLE
Rejecting valid Environment Variable Names

### ISSUE THREAD

**Issue by DarqueWarrior** [kubernetes/kubectl#47]
**Kubernetes version:**

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23 15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18 21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure Container Service
- **OS**: Windows 10
- **Install tools**: 
- **Others**:

**What happened**:
I was invoking the following command:
`kubectl run myname --image=myimage:86 --port=80 --env="ConnectionStrings:DefaultConnection=Data Source=tcp:mySqlServer,1433;Initial Catalog=myDB;User Id=myUser;Password=mypassword;"`
I got errors about invalid env:
error: invalid env: ConnectionStrings:DefaultConnection=Data Source=tcp:mySqlServer

I tried this with a YAML file as well and got a better error message stating I was using invalid characters for my name. However, : is valid the only values not allowed in names is "=".  To work around this I removed the : then I got an error because it split my value on "," between my server and port.

**What you expected to happen**:
I expected a new environment variable to be created with the following information:
- name: ConnectionStrings:DefaultConnection
- value: Data Source=tcp:mySqlServer,1433;Initial Catalog=myDB;User Id=myUser;Password=mypassword;

**How to reproduce it** (as minimally and precisely as possible):
Just try and set the environment variable name to something that includes a ":" and have a value that contains a ",".  The splitting should not split on "," in the value of the environment variable. 

**Anything else we need to know**:
I am using .NET Core and it allows you to create nested configurations that are built using a : in the environment variable name.  I was able to use this just fine with docker run commands against my own host because docker and Linux does support the string as I originally submitted it. This only breaks because of the validation of values and parsing logic of kubectl.

**Comment by zjj2wry** [comment]
@DarqueWarrior the env key not support name: "a:b", but value can set value: "a:b".

**Comment by apelisse** [comment]
According to [this](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html#tag_08_01):

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names.

Which let's me believe that we should allow "other characters".

Also, try this:
```
$ python
>>> import os
>>> os.environ["ConnectionStrings:DefaultConnection"] = "Data Source=tcp:mySqlServer,1433;Initial Catalog=myDB;User Id=myUser;Password=mypassword;"
>>> print os.environ["ConnectionStrings:DefaultConnection"]
Data Source=tcp:mySqlServer,1433;Initial Catalog=myDB;User Id=myUser;Password=mypassword;
>>> os.system("env | grep 'ConnectionStrings:DefaultConnection'")
ConnectionStrings:DefaultConnection=Data Source=tcp:mySqlServer,1433;Initial Catalog=myDB;User Id=myUser;Password=mypassword;
0
```

I don't see anything wrong there.

**Comment by pwittrock** [comment]
Fixed in 1.8

https://github.com/kubernetes/kubernetes/commit/b99e57149d81aef8b0bbb3181f851257d18a2569

**Comment by mengqiy** [comment]
https://github.com/kubernetes/kubernetes/pull/47460 doesn't fix this issue with `:`.
Reopening the issue.

**Comment by mengqiy** [comment]
It seems kubectl doesn't like `:` in the env key.

@shiywang Do have bandwidth to verify if this is a bug in Cobra or in kubectl code?

**Comment by mengqiy** [comment]
@shiywang Any update?

**Comment by vithati** [comment]
I wanted to learn more about kubernetes and thus started investigating this issue out of interest. 

@mengqiy , I found that the issue is not in Cobra but in kubectl code. Cobra is parsing arguments properly but kubectl is not allowing ":" in environment name. Allowed characters in environment are [-._a-zA-Z][-._a-zA-Z0-9]* as per this [code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L306). 

Is it ok if I take up this issue and raise PR for the fix?

**Comment by apelisse** [comment]
@vithati Please, feel free to open a PR for this! Thanks (and please assign me).

**Comment by bgrant0607** [comment]
Please see https://github.com/kubernetes/kubernetes/issues/53201

**Comment by pswica** [comment]
I tried resolving this here: https://github.com/kubernetes/kubernetes/pull/78910

**Comment by apelisse** [comment]
There is already a proposal to fix it in https://github.com/kubernetes/kubernetes/pull/69415, and it's not that easy. Though it seems like it's been abandoned. so I'd be happy to see someone pick it up

**Comment by apelisse** [comment]
See also:
- https://github.com/kubernetes/kubernetes/issues/70232
- https://github.com/kubernetes/kubernetes/issues/53201

**Comment by pswica** [comment]
Woah yeah it looks like this had much more history than I expected, and that I'm probably wrong haha.

Would you happen to know why my solution is not good? I basically found that line was the culprit and ran some `fmt.Printlns`. From there I went to a regex tester until I found something that worked. Then I tested against `hack/local-up-cluster.sh` and it worked like a charm.

**Comment by apelisse** [comment]
Your code is perfectly fine. The problem is with backward compatibility. If we start inserting these newly permitted object in the database, it might be a problem when you have multiple masters running at the same time (and not being updated at the same time), or if you fallback your master upgrade to a former version. Then those objects are no longer valid (this is an API change) and will be "stuck" in etcd.

**Comment by pswica** [comment]
That was an amazing explanation. Thanks a lot for taking the time to post that, I can now see that my solution was pretty naive because, in its current state, I can't imagine it being backwards compatible.

**Comment by liggitt** [comment]
/close
in favor of https://github.com/kubernetes/kubernetes/issues/53201 (specifically coordinating in https://github.com/kubernetes/kubernetes/issues/53201#issuecomment-534647130)
